import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

export default function AboutLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <main className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">{children}</main>;
}
